### ISSUE TITLE
Separate stages in Bugsnag

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/researcher-metadata#1023]
Everything that gets sent to Bugsnag from RMD is classified as being from the development stage.  We want these separated (ie development, qa, production).  This will require changes to https://github.com/psu-libraries/researcher-metadata-config .

**Comment by jrpatterson** [comment]
@ajkiessl  Will get Bryan a Bugsnag account.  @bryanlopezrr  If you can then tag/label each environment in K8s to keep them separated that would be great.
