### ISSUE TITLE
Show depositor default embargo terms and other sharing rules during upload process

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#111]
During upload process, query the OA Button Permissions API (or Sherpa Romeo) and display default sharing rules for the particular article version. Sharing rules can include an embargo, a license, and/or a set statement that should accompany deposit. Allow depositor to override these defaults. For items not found in the OAB Permissions API, encourage depositor to contact openaccess@psu.edu.

Implementing shareyourpaper.org (#73) would probably take care of this. Update: We decided not to do that.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez I ran some analysis on the OAB permissions API with a sampling of several thousand Publications we have in RMD.  I also downloaded what OAB claims to be all their data as a CSV.  What I was finding in the API seems to match up with the CSV, except that I was finding some publications in the API with a "cc0" license and "None".  The comprehensive list looks like this:

CC-BY-NC-ND
CC-BY-NC
Other (non-commercial)
Other-closed
CC-BY-NC-SA
unclear
CC-BY
CC-BY 3.0
CC-BY 4.0
cc0
None

Here is what's in our dropdown:

![Screen Shot 2022-09-15 at 12 57 32 PM](https://user-images.githubusercontent.com/32677188/190463613-552f5df9-2cec-4d98-9a67-32389bafda8e.png)

Some of the licenses look like they map to something in our dropdown.  Perhaps we can just ignore ones that are "None", "unclear", or blank.  The "Other-closed" and "Other (non-commercial)" ones I am not too sure about.  Also, there is one that is just "CC-BY" and another that is "CC-BY 3.0" that I'm not too sure about either.  Do you know if these can be mapped to anything we have?

**Comment by anaelizabethenriquez** [comment]
Here's how I would map (I think we can map everything):

| API value | RMD list |
| ------------- | ------------- |
| CC-BY-NC-ND | CC BY-NC-ND 4.0 |
| CC-BY-NC | CC BY-NC 4.0 |
| Other (non-commercial) | All rights reserved |
| Other-closed | All rights reserved |
| CC-BY-NC-SA | CC BY-NC-SA 4.0 |
| unclear | All rights reserved |
| CC-BY | CC BY 4.0 |
| CC-BY 3.0 | CC BY 4.0 |
| CC-BY 4.0 | CC BY 4.0 |
| cc0 | CC0 1.0 Universal |
| None | All rights reserved |
