### ISSUE TITLE
Automate data that prevents nudge email

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#113]
In addition to articles with OA link in RMD, the following articles should not get a nudge:

- Article is deposited in ScholarSphere with or without embargo
- Article is in process of deposit to ScholarSphere via AI
- There is a waiver for article (through RMD or alternate form)

For the initial batch, we'll do this manually, but it would be nice to automate what we can, down the line.

**Comment by ajkiessl** [comment]
Bullet point 1 and 3 above are done so we only need to do 2.  We should be able to this with the post print statuses we are now getting from AI.

**Comment by ajkiessl** [comment]
If post_print_status is 'In Progress' we want to suppress emails

**Comment by anaelizabethenriquez** [comment]
I just merged two duplicates (merging an AI import publication into a Pure import one, as is our usual practice) and noticed that "Activity Insight postprint status" is now blank on the merged publication. Prior to the merge, the AI import publication had this data, but (of course) the Pure import publication did not. The publication is 415198. Perhaps when the AI import runs next, we'll get that data again? If not, we'll need to address this in order to suppress emails for all publications that have an "In Progress" status in Activity Insight.

**Comment by ajkiessl** [comment]
Yeah, the AI import should pick this up, but we should also add something into the merging logic that keeps the post print status in these cases.  I'll add an issue.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl I was just thinking about how we suppress OA reminder emails for publications with post_print_status of "In Progress". With our new workflow, are we setting the post_print_status to "In Progress" when a file gets imported to RMD, or is the post_print_status data now out of date?

**Comment by ajkiessl** [comment]
@anaelizabethenriquez We do update the post_print_status on import, but it's set to whatever value has been chosen in Activity Insight.  This value is tied to the file in Activity Insight, so if there's a file, there's a status (but not necessarily a status of "In Progress").  We do not automatically set the status to "In Progress" if it is not "In Progress".

> is the post_print_status data now out of date?

Are you asking here if the post_print_status is no longer useful to use as a filter for the OA email notifications?  If so, I would say potentially yes.  If the Activity Insight admins (or whoever typically sets this) can continue to update this field, then it could still be useful.  We could change the importer to update this field or we could filter out any publications that have an attached `ActivityInsightOAFile` from the OA email notifications.
