### ISSUE TITLE
Look up Publications in OA Button and/or Unpaywall based on fields other than DOI

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#162]
Two reasons to do this:

1. RMD doesn’t have the DOI (maybe it doesn’t exist) 
2. The repository doesn’t have the DOI (but RMD might) 

URL, DOI, and Title all appear to be options for querying the OA Button API. Not sure about Unpaywall.

**Comment by Smullz622** [comment]
for unpaywall: will need to handle if more than one result returned, consider only allowing certain publication types (merge_allowed types)
