### ISSUE TITLE
Publication status regresses from "published"

### ISSUE THREAD

**Issue by awead** [psu-libraries/researcher-metadata#207]
Articles can return to a previous "in press" state from being published. We need to account for this change by looking at the daily imports from Digital Measures to see if anything has changed.

Needs further discussion with PO and stakeholders.

**Comment by ajkiessl** [comment]
In the current state of the code, this should already be happening.  Except in the case that a user has made edits to a publication (which could potentially be a lot of publications).

**Comment by ajkiessl** [comment]
If a publication has been edited by an admin, it should still update status.

**Comment by anaelizabethenriquez** [comment]
Related to #465

**Comment by anaelizabethenriquez** [comment]
Related to #465
