### ISSUE TITLE
Adapt existing importers to open access data model

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/researcher-metadata#256]
The following importers store data in the deprecated `open_access_url` field in the `Publication` model:

- https://github.com/psu-stewardship/researcher-metadata/blob/main/app/importers/open_access_button_publication_importer.rb
- https://github.com/psu-stewardship/researcher-metadata/blob/main/app/importers/scholarsphere_importer.rb
- https://github.com/psu-stewardship/researcher-metadata/blob/main/app/importers/oai_importer.rb

Instead of using this field, these importers should create a new `OpenAccessLocation` record  (see https://github.com/psu-stewardship/researcher-metadata/issues/192) that is associated with the publication or they should update such a record if one already exists.

**Comment by EricDurante** [comment]
Indeed. I had forgotten about that one. The source should probably be the name of whichever PSU Law repository the metadata came from.

**Comment by anaelizabethenriquez** [comment]
I _think_ that's coming from two repositories (one for each of the two law schools): [Dickinson IDEAS](https://ideas.dickinsonlaw.psu.edu/) and [Penn State Law eLibrary](https://elibrary.law.psu.edu/).

**Comment by EricDurante** [comment]
Yep, ☝️ that's correct.
