### ISSUE TITLE
Update swagger_ui_engine

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/researcher-metadata#264]
The latest version of `swagger_ui_engine` gem does not support Rails 6. There are a few options for how to proceed:

- replace `swagger_ui_engine` with `rwsag`, which is better maintained and supports Rails 6: https://github.com/rswag/rswag#route-prefix-for-swagger-json-endpoints
- update to the unreleased v1.1.4 of `swagger_ui_engine`: https://github.com/zuzannast/swagger_ui_engine/tree/1.1.4-version
- roll this ourselves without a gem

It seems to me that the `rswag` route might be the best option for long-term maintainability, since `swagger_ui_engine` seems to be abandoned at this point.

**Comment by EricDurante** [comment]
There's one other option - we could become the de facto maintainers of `swagger_ui_engine`. That's probably more than we want to get into though.

I'd vote for attempting to use `rswag` first as long as it has feature parity with `swagger_ui_engine`.
