### ISSUE TITLE
Update Node.js

### ISSUE THREAD

**Issue by awead** [psu-libraries/researcher-metadata#324]
Currently, CI uses the latest LTS version of node. See https://nodejs.org/en/download/ for the details, but right now it's listed as 16.13.0, but CI is tell us it uses 14:

![Screen Shot 2021-10-29 at 10 19 15 AM](https://user-images.githubusercontent.com/312085/139451460-2a014ec6-8f35-452c-b171-65bd928e561a.png)

We should update our servers to match the version that CI is using.

## WDLL

* update node on QA, stage and production to 14
* update `.node-version` file to reflect this version as well

## Issues

There isn't an easy way to keep the local, CI, and server versions all in sync, it's really just bookeeping. The `.node-version` file should represent the version that's being used on the deployments, and should also ideally be what we use in our local environments as well. The CI build's versions will change, but we can see that happen in the output of each run. As the CI version changes, we can change our deployed version as needed.

**Comment by ajkiessl** [comment]
New issue for docker-compose work: #896
