### ISSUE TITLE
OAI Importer Bug

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/researcher-metadata#328]
Need some `nil` handling here:

NoMethodError: undefined method `text' for nil:NilClass

![Screen Shot 2021-10-29 at 4 43 03 PM](https://user-images.githubusercontent.com/32677188/139499429-123a9af9-7e60-498f-8c3f-31ee501617fa.png)

**Comment by awead** [comment]
`try(:text)` is probably the easiest.
