### ISSUE TITLE
Managing Postgresql locally

### ISSUE THREAD

**Issue by awead** [psu-libraries/researcher-metadata#342]
The newest version of Postgres (as of this writing) is 14. When installing that locally, it makes changes to the schema.rb file:

```
@@ -423,7 +423,7 @@ ActiveRecord::Schema.define(version: 2021_11_03_180127) do
     t.boolean "exported_to_activity_insight"
     t.string "open_access_status"
     t.datetime "unpaywall_last_checked_at"
-    t.index "date_part('year'::text, published_on)", name: "index_publications_on_published_on_year"
+    t.index "EXTRACT(year FROM published_on)", name: "index_publications_on_published_on_year"
     t.index ["doi"], name: "index_publications_on_doi"
     t.index ["duplicate_publication_group_id"], name: "index_publications_on_duplicate_publication_group_id"
     t.index ["issue"], name: "index_publications_on_issue"
```

The deployed version is 12, and it's likely that these changes to the schema would _not_ work under the older version. This means that we need a way to keep our local postgres version in sync with the deployed version.

## Options

1. Manage locally (keep version 12 installed)
2. Use docker-compose

My personal preference is docker/docker-compose at this point because installing older versions of postgres via brew can be difficult. The Penn State devs already have it for other apps, so switching over would be relatively painless.

## Issues

It's not necessary to do this right now, but anyone updating the postgres locally will get the new version.

**Comment by ajkiessl** [comment]
Closing this since #896 covers this
