### ISSUE TITLE
Enable remaining Rails 6.1 new framework default settings

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/researcher-metadata#346]
Once we upgrade to Rails 6.1 and have been in production for a bit, we should enable the remaining non-backwards-compatible new framework default settings located in `new_framework_defaults_6_1.rb` and fix any issues that arise.

Once those are working, we can then change the `config.load_defaults` setting in `application.rb` to `6.1` and fix any issues that arise as a result of that change.

Some issues that I expect to arise:

- Rails 6 uses `zeitwerk` to load code, and this introduces some issues related to class naming conventions. Our current thought process is to remove any inflections from `initializers/inflections.rb` and rename any classes that `zeitwerk` doesn't like. You can check for zeitwerk problems by running `bundle exec rake zeitwerk:check`.
- Rails Admin custom actions will need to be moved from `app/rails_admin_actions` to `lib/rails_admin/config/actions` to make zeitwerk happy.

**Comment by ajkiessl** [comment]
Done in #705
