### ISSUE TITLE
Publications have more than one ScholarSphere link

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#354]
I've noticed that 296 of the 697 RMD publication records with OA locations with source of ScholarSphere have more than one OA location with source of ScholarSphere. There are a couple innocuous (to us) things that could cause this:

- The article has actually been deposited more than once in ScholarSphere. (This isn't a desired outcome, but in this situation it's reasonable for RMD to have URLs for both deposits.)
- An extra ScholarSphere URL got added by an RMD user. (I'm not sure this is possible for regular users, because the source for those would be "User," but admins at least could have added an OA Location with a source of "ScholarSphere.")
- The same URL appears more than once. (Not sure if this is possible.)

I want to make sure this isn't a problem with the importer, either grabbing version URLs or grabbing ScholarSphere deposits that aren't articles (e.g., the data that supports the article).

- Version URLs: Works in ScholarSphere have URLs for the work and URLs for versions of the work. Ideally, RMD would only contain the work URLs. In public uses like the Huck profiles site, it's not ideal to display a version URL, which could take a visitor to an outdated version of the work. Using the work URL ensures the visitor gets the most current version. While having some version URLs in RMD is OK, we should ensure that ScholarSphere URLs added by the importer are work URLs.
- Non-article ScholarSphere deposits: The OA Location field in RMD should only contain OA links that point to copies of the article itself (including various versions of it). It should not contain links to ScholarSphere deposits of data, images, etc.

Examples:

- [Publication 112561](https://metadata.libraries.psu.edu/admin/publication/112561) has 6 associated ScholarSphere links, none of which is for an article file.
- [Publication 284682](https://metadata.libraries.psu.edu/admin/publication/284682) has 2 associated ScholarSphere links, one of which is a version link and one of which is a work link.

**Comment by awead** [comment]
We could potentially make the ScholarSphere linking process _only_ link to works and not versions. The first example was imported, and not added to Scholarsphere directly since the upgrade. Some of the problems associated here are that works where uploaded a individual files, instead of a single work with multiple files. I suspect this is the case with that first example.

**Comment by anaelizabethenriquez** [comment]
Looping in @srerickson

**Comment by srerickson** [comment]
see https://github.com/psu-libraries/scholarsphere/issues/1164

**Comment by ajkiessl** [comment]
This was completed in ScholarSphere so we may just want to run an import in a test/qa instance to double-check that we are only pulling in one ScholarSphere url per publication.  We may also want to consider what we want to do about the publications that now have more than one SS OA location.

**Comment by ajkiessl** [comment]
To remove the unwanted Scholarsphere links we will have to delete all the Scholarsphere links and then re-run the Scholarsphere import.

**Comment by banukutlu** [comment]
We removed all Scholarsphere links and ran the SS importer to generate them, the total number of links went down, Ana also checked them and it all looked good.
