### ISSUE TITLE
ScholarSphere importer should not import URLs for works in "Draft" state

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#355]
The importer that brings in URLs from ScholarSphere should not import URLs for works in "Draft" state. 

I can't tell whether the importer is doing this as currently written or not. I have one example of a publication ([282947](https://metadata.libraries.psu.edu/admin/publication/282947)) that has an OA Location with source ScholarSphere and a [URL for a Draft work](https://scholarsphere.psu.edu/resources/c93c1519-65f0-4954-974c-bf4d0c682357).

This doesn't quite seem like a bug, so I'm not tagging it as such. But I am tagging @ajkiessl so he gets a notification and can clean up this ticket as needed.

**Comment by ajkiessl** [comment]
Related: #354 .  These both could be fixed at the same time, depending on how we can change the ScholarSphere API.  An endpoint that only gives us the primary work (not versions, drafts, or ancillary documents) would be great.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl @srerickson We should also think about excluding ScholarSphere works that aren't scholarly articles. Officially, users shouldn't be putting an article's DOI in ScholarSphere's Publisher Identifier field unless the ScholarSphere work is that article. But, looks like there are ScholarSphere deposits like this (e.g., those linked to [Publication 112561](https://metadata.libraries.psu.edu/admin/publication/112561), such as https://scholarsphere.psu.edu/resources/c91c6173-77f6-4907-ad71-fc36b3eaaf45). Potentially we could exclude some ScholarSphere work types (e.g. "Dataset") from the importer?

**Comment by ajkiessl** [comment]
Yes, potentially.  Right now we aren't receiving any metadata from the Scholarsphere API to help us differentiate between different work types.  So, either Scholarsphere will have to start supplying us with that metadata (then we would have to modify our importer to do the differentiating), or Scholarsphere can just give us an endpoint that only gives us what we want.

**Comment by ajkiessl** [comment]
Since we are only returning links to the most recent published version of a work in the Scholarsphere API, this should be complete when #354 is complete.

**Comment by ajkiessl** [comment]
closed with #354
