### ISSUE TITLE
Refresh user identity information with PSU Identity API

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#388]
Identity information for existing RMD users, including names, should be refreshed periodically from the Penn State Identity API. Ideally we should refresh this pretty frequently, so that we're not using out-of-date names in public profiles or OA reminder emails.

Users make these changes at https://accounts.psu.edu/manage. We can refer them there and ensure we're refreshing data frequently to get those changes. We can also make changes to their name in RMD.

**Comment by ajkiessl** [comment]
When implementing this, move `User.update_psu_identity` to the `PsuIdentityUserService` class.  The `update_psu_identity` method probably doesn't belong in the `User` if we have a service and we are doing bulk updates.

**Comment by ajkiessl** [comment]
This is something that should be run before OA email notifications go out.

**Comment by ajkiessl** [comment]
Since we will be running the OA email task weekly we should run this at least weekly.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez In the case that an admin has edited a User record (potentially editing the User's name), do we still want the importer to overwrite these changes?  I think this would be preferred, since we would like identity services to be the central authority on names.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl Yes, I agree. I think the importer should overwrite changes.

**Comment by ajkiessl** [comment]
Cron jobs are configured here: https://github.com/psu-libraries/researcher-metadata-chef/blob/f625fafd7636baa0cdcaaf472d6332e0821c1c72/cookbooks/psu_research_metadata/recipes/production.rb
