### ISSUE TITLE
AI IDs associated with 0 or multiple RMD records

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#413]
@srerickson has been querying the RMD API by AI ID and gotten some unexpected results. Quite a few of the IDs he's looking for have either zero records in RMD or more than one record (up to 12). Seems like this might have something to do with duplicates, but I'm not sure exactly what. This is not blocking our work, it's just very unexpected.

These AI IDs are coming from Activity Insight exports that @nmg110 's team runs for publications where the researcher uploads a post-print in RMD. They can have a variety of document types in AI (not necessarily journal articles). 

Here are examples of AI IDs with no records associated:

222649597952
218823843840
214945056768
218861940736
219108661248

Here are examples of AI IDs with more than one record associated:

196613644288 (3 records)
203850590208 (2 records)
214769737728 (12 records)
214769721344 (12 records)
218180702208 (11 records)

**Comment by ajkiessl** [comment]
@anaelizabethenriquez I released a patch to production that fixes the issue with the duplicates.  There was a bug causing this.  The API was returning a record for every organization the users associated with that publication were a member of.

I'm still looking into why some AI IDs are not returning any records.  The records you listed above don't appear to be in RMD, so they must not be getting imported.  Not sure why that is, but still looking.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Looking at the records for those AI IDs in Activity Insight: 218861940736, 214945056768, and 218823843840 don't have statuses of "Published" or "In Press", so they weren't imported for that reason.  222649597952 and 219108661248 look like they should have been imported without issue, however, I am noticing that the error handling in the Activity Insight importer is not ideal.  I added a ticket to address this here: #417.  Basically, the importer will stop importing data for a user if it encounters any kind of error and move to the next user.  Something like a missing title could cause an error.  This is likely the reason these publications are not being imported.  It's hard to pinpoint exactly what the error is and there could potentially be multiple errors.  For example the user (sjc2) for record 219108661248 has a handful of publications in Activity insight that do not have titles.  

This is probably something that should be prioritized in a future development cycle.  I think this was potentially what we wanted to address here: #188, but it was not fixed quite the way it needed to.  I have a better understanding of the magnitude of the issue now.

**Comment by anaelizabethenriquez** [comment]
Thanks, Alex. I agree about prioritizing this on a future development cycle. 

I'm tagging @srerickson so he will be aware of this outcome and @nmg110 so she knows RMD isn't importing as much from AI as we thought.
