### ISSUE TITLE
Include `activity_insight_postprint_status` in API

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/researcher-metadata#423]
It would be useful for our workflow if the `activity_insight_postprint_status` field were part of the publication metadata available through the API (i.e., GET /v1/publications/{id}).

**Comment by anaelizabethenriquez** [comment]
We wanted this feature to use with the AirTable version of the AI OA workflow. Now that we are no longer using AirTable, I don't see any reason to do this.
