### ISSUE TITLE
RMD user with incorrect name order

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#434]
I have noticed that for user 711 (czr58), the order of the names is wrong. Other PSU sites, and this person's email signature, use the "displayName" we are getting from Penn State Identity. RMD is using the two names from the displayName, but with the order switched. In addition to not matching displayName, this does not match either the "givenName" "familyName" pair or the "preferredGivenName" "preferredFamilyName" pair in Penn State Identity.

In the next development round, can we review this to figure out what's causing the error? And now that we're importing values from Penn State Identity, can we explore using "preferredGivenName" "preferredFamilyName" for public profiles, emails to users, and other user-facing or public-facing uses?

In the meantime, is it OK if I fix this one manually? Thanks!

**Comment by anaelizabethenriquez** [comment]
May be related to #388

**Comment by ajkiessl** [comment]
## To Do

For user and public facing displays, use the "preferredGivenName" and "preferredFamilyName" from the PsuIdentity info instead of the stored first and last name if they exist.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Just an FYI.  For the first part of this issue regarding czr58 and the first + last names being in the wrong order, this was because the names are switched in Activity Insight and it must have been imported that way.  @nmg110 We should fix this in AI.

**Comment by ajkiessl** [comment]
closed by #505
