### ISSUE TITLE
Open access URL validation may not be working correctly in some cases again

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/researcher-metadata#459]
See https://github.com/psu-stewardship/researcher-metadata/commit/f3a8476285d409babb6b083835c10085f6b7f888

**Comment by anaelizabethenriquez** [comment]
@banukutlu here are the top domains that I see in the user-submitted URLs in RMD (of course, this only includes URLs that successfully validated at the time they were submitted).
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/aee32/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/aee32/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Domain | Number of items
-- | --
doi.org | 237
arxiv.org | 101
www.ncbi.nlm.nih.gov | 72
gcn.gsfc.nasa.gov | 62
sites.psu.edu | 50
lsvr.psu.edu | 46
www.researchgate.net | 43
infolab.stanford.edu | 41
onlinelibrary.wiley.com | 37
reader.elsevier.com | 37
www.academia.edu | 34
zeus.plmsc.psu.edu | 30
personal.psu.edu | 29
scholarsphere.psu.edu | 28
pubmed.ncbi.nlm.nih.gov | 26
academic.oup.com | 25
link.springer.com | 25
www.tandfonline.com | 22
pubs.rsc.org | 21
journals.sagepub.com | 20
www.astronomerstelegram.org | 19
iopscience.iop.org | 18
par.nsf.gov | 17
pubs.acs.org | 17
www.sciencedirect.com | 17
www.personal.psu.edu | 15
www.frontiersin.org | 11
www.mdpi.com | 11
europepmc.org | 10



</body>

</html>
