### ISSUE TITLE
Automatically send open access reminder emails weekly

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#463]
- Should be timed so imports have all run just before the email goes out. 
- Emails should not go out if the most recent OA Button and/or Unpaywall imports failed or have a certain amount of errors.
- Sending these weekly is ideal for smoothing out the workload on answering support tickets. However, we may want to be able to cancel them for a particular week if there are vacations or holidays.
- Ideally the auto-deduplication (#468 ) would run before each email batch.
- It would be nice to cap the total number of emails that can be sent in one week. Otherwise, we'll send a very large batch exactly six months after the last large batch.

**Comment by ajkiessl** [comment]
Cap emails sent to 300/week
