### ISSUE TITLE
Publications that have been edited by admins have outdated data

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#465]
As I understand it, RMD freezes data in a publication record if the record has been edited by an admin. This includes edits made during the manual de-duplication process. I've noticed a lot of records get stuck with a status of "In Press" because of this. On its own, that may not be a big problem, but I'm wondering if there are other data integrity problems related to this "freezing."

@ajkiessl

**Comment by ajkiessl** [comment]
At a quick glance, the only thing that continues to update from Activity Insight after a user has edited is `activity_insight_postprint_status` .  For the Pure import the only things that continue to update are `total_scopus_citations`, `journal`, and `doi` if the doi is blank.

**Comment by anaelizabethenriquez** [comment]
To fix items whose publication status is stuck in "In Press," I wonder if we could search for items in that status that have a publication date and then bulk-change their statuses to "Published." If we can just refresh the data from Pure/AI, that's probably better, but I'm not sure how that should work for merged records.

**Comment by anaelizabethenriquez** [comment]
We should likely update "title" as well, at least if there's just one import on the publication (i.e. the publication data is not the result of a merge). I am seeing a lot of items in Activity Insight exports where the title changes.

**Comment by anaelizabethenriquez** [comment]
Allowing the importer to update the title even when the record has been edited will also ensure that the improvements from #396 get applied to as many publications as possible.
