### ISSUE TITLE
Assess article version during deposit process

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#467]
When a user uploads a file to deposit, attempt to check the article version. If one can be determined, display it to the user and give deposit advice accordingly (this could be very general or could be based on #111 ). If version cannot be determined, tell the user that and perhaps allow them to indicate an article version for the purposes of #111. If user is trying to upload something other than an accepted manuscript or a final published version, encourage them not to. (OA policy requires accepted manuscript. Final published version is even better, so we'll take that if they are allowed to share it.)

**Comment by ajkiessl** [comment]
Here's the code that parses metadata from files: https://github.com/psu-libraries/fams_tools/blob/main/app/models/verify_post_print.rb .  It uses the `PDF::Reader` and `Exiftool` gems to do this.

**Comment by ajkiessl** [comment]
Here's the chunk that looks at article version: https://github.com/psu-libraries/fams_tools/blob/main/app/models/verify_post_print.rb#L106-L126

**Comment by anaelizabethenriquez** [comment]
### Some clues for determining article version (besides code Alex shared above):
Metadata field called "Journal_article_version" (or perhaps jav:journal_article_version) -- This field is extremely reliable if we have it, but it's often blank/not present: 
- If "VoR," this is the final published version, aka version of record -- generally not depositable
- If "P," this is the proof, which for our purposes (including for #111) is the same as the version of record -- generally not depositable
- If "AM," this is the accepted manuscript, aka "postprint" -- what we are aiming for; generally depositable

[Exif fields for determining article version](https://pennstateoffice365.sharepoint.com/:w:/r/sites/OpenAccessPolicyInfrastructure/_layouts/15/Doc.aspx?sourcedoc=%7BDE114F3E-30DA-4309-80EF-65EB036B2A02%7D&file=Exif%20fields%20for%20determining%20article%20version.docx&action=default&mobileredirect=true) -- I wrote up this doc with some fields that I think indicate the file is the final published version.

[Identifying Post-Prints](https://pennstateoffice365.sharepoint.com/:w:/r/sites/OpenAccessPolicyInfrastructure/_layouts/15/Doc.aspx?sourcedoc=%7B6A6F459A-B4FC-4204-9891-4995923175BB%7D&file=Identifying%20Post-Prints.docx&action=default&mobileredirect=true) -- This doc was designed for people who are looking at individual files, so it's probably not directly useful to you, but could still give an overview of the issue.

[What are the different versions of scholarly articles?](https://psu.libanswers.com/faq/273465) -- This is the user-facing documentation on this issue. The "pre-print" option is basically irrelevant to this feature. It's almost impossible for a computer to tell the difference between a pre-print and an accepted manuscript. We'll have to count on the uploader to figure that out.

Examples of post-prints, aka accepted manuscripts:
[March post-prints](https://pennstateoffice365.sharepoint.com/:f:/r/sites/OpenAccessPolicyInfrastructure/Shared%20Documents/Identifying%20Post-Prints/March%20post-print%20examples?csf=1&web=1&e=GoyQeq)
[April post-prints](https://pennstateoffice365.sharepoint.com/:f:/r/sites/OpenAccessPolicyInfrastructure/Shared%20Documents/Identifying%20Post-Prints/April%20post-print%20examples?csf=1&web=1&e=iRo2U3)

Finally, I believe [ShareYourPaper](https://shareyourpaper.org/) has implemented some kind of version checker, and the project is supposed to be open source, so you may be able to find that.

**Comment by anaelizabethenriquez** [comment]
@banukutlu I was just getting ready to email Joe McArthur at OA.Works about this. Before I do that, I wonder if @DanCoughlin can share anything about the feasibility of our implementing OA.Works's [ShareYourPaper](https://shareyourpaper.org/). I know he's explored that (#73), and I thought we'd ruled it out due to platform incompatibility with ScholarSphere. I'm wondering if we need to explore it further. It's at least theoretically compatible with local IRs now (not just Zenodo). If it's usable, it would handle this issue as well as #111, so I'm tagging @ajkiessl

**Comment by DanCoughlin** [comment]
@anaelizabethenriquez my recollection was that we were able to implement similar functionality (look up paper by DOI, and return paper metadata) more simply ourselves than trying to implement OA.Works solution. At that time there was concern about the reliability and durability of the API. At times it had changed and wasn't versioned for us to get a heads up about it. Some of the things we required to implement on our end required development on their end as well and (at that time) it seemed simpler to continue our own path. Is there something specifically they do, that we want?

**Comment by anaelizabethenriquez** [comment]
@DanCoughlin We are hoping to implement article version checking (this issue), which ShareYourPaper does and RMD doesn't do yet. Connected to that, we will use the DOI to fetch permissions info for that article version from their Permissions API (#111 ). (Of course there is other stuff SYP does that RMD already does, like sending the deposit to the IR.) So I'm wondering if we're crossing the line into using so much OA.Works/ShareYourPaper stuff that it would be easier to just implement SYP. @ajkiessl

**Comment by DanCoughlin** [comment]
@anaelizabethenriquez my guess is that it is simpler for us to use their API then implement their solution. My bigger concern, based on the number of dependency issues that straining our resources in several areas, is which is likely to have a longer shelf life. It's a bit of a guessing game, but my sense is the API may have an easier path forward for maintenance then bringing in the OA.Works screen. However, that's completely an assumption, I haven't looked at it enough. @ajkiessl may have more thoughts.

**Comment by ajkiessl** [comment]
I agree.  Considering how far we've gotten with the ScholarSphere uploads, it's probably simpler to use the API.  Also, using the API gives us more flexibility on how we want to implement things.  I suppose their version checker would be nice to have, but theirs might be just as limited as ours 🤷‍♂️ .

**Comment by anaelizabethenriquez** [comment]
OK, thank you both @DanCoughlin @ajkiessl ! Per our original plan, I'm going to email Joe McArthur about finding the code for the version checker, and I will copy Banu.

**Comment by anaelizabethenriquez** [comment]
@banukutlu Here's a little more that I hope will be helpful.

Alex is setting up #111 to take two possible values -- either the file is the accepted manuscript (also called the post-print) or it is the final published version. Ideally, this version checker should:

1. Look at the journal_article_version tag.
a. "AM" = Accepted Manuscript
b. "P" = Proof -- Treat this as the final published version.
c. "VoR" = Version of record, that is, the final published version
2. If the journal_article_version tag is not present, or if the value isn't one of the options above, look at other factors to make a guess at whether the file is the accepted manuscript or the final published version. (Hoping that ShareYourPaper has logic you can use here -- I copied you on my email to Joe McArthur.)
3. Display the result to the user and give them a chance to override it before fetching the permissions for sharing that version (which is covered by #111). Text could be, "This looks like the [accepted manuscript]/[final published] version of the article. Should we fetch the article sharing rules for that version of the article?" Choices: "Yes" or "No, this is the [final published]/[accepted manuscript] version. Fetch the sharing rules for that version instead."
a. Depending on how step 2 goes, you could also display something like "We have not been able to determine automatically which version of the article this is. Please select the correct article version so we can fetch the sharing rules for the article." And then you'd offer both choices. We could link to the [FAQ about article version](https://psu.libanswers.com/faq/273465) to help people evaluate this.
