### ISSUE TITLE
Run auto-deduplication on an automated basis

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#468]
This would be very nice to do for #463. It would also reduce needless manual deduplication of automatable duplicate groups.

Tagging @ajkiessl in case there is more to say here.

**Comment by ajkiessl** [comment]
We've talked about two potential ways of doing this.  

1. The way our merge methods are built, a merge can be invoked on a single publication.  Therefore, we could run the merge process for every publication during imports.  This would require implementing the merge process in the desired importers, and could potentially slow down the imports a bit.

2. The other way would be to just run our merge rake tasks (that iterate through all publications and invokes merges) on a regular cron job.  This would preferably be done right before emails go out.

The benefit of doing # 1 would be that publication auto-merging will always be up to date, and we don't have to concern ourselves with running and timing a cronjob before emails go out.  The downside of # 1  would be that the merge process will have to be implemented in multiple places and that it might slow the import process a bit.

**Comment by ajkiessl** [comment]
Another note:  We have two merge methods for `Publication`.  Regular `.merge!` which only applies to publications imported from Pure and Activity Insight, and `.merge_on_doi` which applies to all publications.

**Comment by ajkiessl** [comment]
Went with choice # 2 above.  We know these tasks work, and to get us rolling with weekly emails it will probably be safer.  We can still add the automerge on import in the future if we'd like.
