### ISSUE TITLE
Publications with same publication date and same DOI were not automatically merged

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#474]
I ran across a pair of publications today that I believe ought to have been automatically merged, and I can't figure out why they weren't. I have since merged them, but I took a screenshot (attached). The publication IDs were 293849 and 280281
<img width="1151" alt="Screen Shot 2022-07-25 at 1 41 24 PM" src="https://user-images.githubusercontent.com/43611017/180867611-0c30950f-9903-4677-bc9c-6ef4e8b544e2.png">
.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez The ISSNs are the reason these two did not merge.  The criteria for ISSNs to match are: one ISSN is blank and the other is not, or one ISSN is contained inside the other, or the ISSNs match exactly.  We can loosen these requirements or remove them completely if we think that would be okay.

**Comment by anaelizabethenriquez** [comment]
Thanks @ajkiessl. I would at least loosen this so that issns of XXXX-XXXX and XXXXXXXX are considered a match, but I think we could entirely remove the requirement that ISSNs match. 

The main false match that I want to prevent is a match on two items called "Preface" or "Introduction" or something else generic like that. ISSNs would help but not entirely prevent false matching there, due to some journals having an Introduction (or similarly generically named piece) in every issue. So DOIs are doing the real work here, and I think we can ignore ISSNs as long as the DOIs match.

**Comment by ajkiessl** [comment]
## To Do

Remove ISSN match requirement in `PublicationMatchOnDoiPolicy`.
