### ISSUE TITLE
Upgrade remaining 5 servers to 18.04

### ISSUE THREAD

**Issue by njnash** [psu-libraries/researcher-metadata#49]
6 PSU VM's. 5 on Ubuntu 16.04, 1 on 18.04. 18.04 was released on 2019-02-15

Aha! Link: https://penn-state-university-libraries.aha.io/features/MDDB-10

**Comment by EricDurante** [comment]
This may need to be changed to "upgrade all servers to Ubuntu 20.04 at this point (assuming that PSU VM Hosting supports Ubuntu 20.04).

**Comment by off2seethewizard** [comment]
Nodes are currently on Ubuntu 20.04.4 LTS - closing issue.
