### ISSUE TITLE
12-factor configuration

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/researcher-metadata#506]
To better support our Kubernetes deployments, We should promote environment specific into ENV variables. 

we should be able to do this by copying all the `.sample` configuration files into their `.yml` counterparts, and replacing the values with ERB ENV calls. 

We could also refactor how the app pulls its configuration and use something like `figaro` or `config` This option I think will require more effort.

**Comment by whereismyjetpack** [comment]
We are using the `config` gem in catalog and I'd like to use config gem here, too if at all possible. What are your thoughts, @ajkiessl @EricDurante

**Comment by ajkiessl** [comment]
That's fine with me @whereismyjetpack
