### ISSUE TITLE
Does RMD's ScholarSphere integration set "depositor"?

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#513]
When an RMD user deposits a work in ScholarSphere using RMD, the "depositor" in ScholarSphere should be the user who deposited the work. (Or, in the case of a proxy/deputy or admin depositing on behalf of another user, the depositor should be the primary.)

Is this currently how things work? The reason this matters is that the "depositor" receives statistics emails from ScholarSphere and has the ability to edit the deposit. I suspect this is happening, but @bdezray and I want to confirm.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Sorry for the delay on this.  That is correct, the "depositor" is the user depositing the work or the primary (not proxy/deputy) that the work is being uploaded for.

**Comment by anaelizabethenriquez** [comment]
Thanks!
