### ISSUE TITLE
Create new automerge process

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#532]
In addition to the existing AI-Pure automerge process and the DOI-based automerge process, we want to create another process that matches when the publications are very similar but one or both don't have DOIs. Like the DOI-based automerger, it should review (and, if appropriate, merge) each pair of publications in a duplicate group.

The starting point for the criteria should be what's currently in the DOI-merge process (prior to the changes in #529 ), but with the following updates:

1. Title and subtitle: Add requirement that the combined title and subtitle of the two publications fuzzy match at a very high percent -- perhaps 90 or 95%.
2. DOI: If the DOIs conflict, do not merge. OK to merge if neither pub has a DOI or if only one pub does.

Background discussion is in #523

**Comment by ajkiessl** [comment]
@anaelizabethenriquez We also need to determine how we want to merge these.  We could use the merging policy that we use for the DOI automerger, so we'd rename PublicationMergeOnDoiPolicy to PublicationMergePolicy and use that.  I think it does a decent job of picking the best data.  Or have some other way to determine the better record.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl Using the policy that's currently used for the DOI automerger sounds good to me.
