### ISSUE TITLE
Update publication type merge logic

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#533]
Both in the DOI-based automerge process and in the new automerge process (#532 ), we require a match on publication type. Since AI and Pure use different vocabularies for these, we should update the logic to allow additional publications to be merged.

Blocked by #532 
Background discussion is in #523

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Here are the publication types we store in RMD:

'Academic Journal Article', 'In-house Journal Article', 'Professional Journal Article',
      'Trade Journal Article', 'Journal Article', 'Review Article', 'Abstract', 'Blog', 'Book', 'Chapter',
      'Book/Film/Article Review', 'Conference Proceeding', 'Encyclopedia/Dictionary Entry',
      'Extension Publication', 'Magazine/Trade Publication', 'Manuscript', 'Newsletter',
      'Newspaper Article', 'Comment/Debate', 'Commissioned Report', 'Digital or Visual Product',
      'Editorial', 'Foreword/Postscript', 'Letter', 'Paper', 'Patent', 'Poster',
      'Scholarly Edition', 'Short Survey', 'Working Paper', 'Other'

**Comment by anaelizabethenriquez** [comment]
@Smullz622 Here's what I recommend:

Publication type merger rules (for use when the DOIs match (DOI automerger) or when lots of metadata matches (#532)):

- OK to merge if one publication's PT is "Other" (This rule already exists on the DOI merger.) The PT after the merge should be the non-"Other" PT.
- OK to merge if both publications' PTs are the same (I suspect this already exists too.)
- OK to merge if both publications are journal articles of some kind (any of the following: 'Academic Journal Article', 'In-house Journal Article', 'Professional Journal Article','Trade Journal Article', 'Journal Article'). The PT after the merge should be just "journal article."  (This is different from the current DOI automerger, because of the update to which publications are subject to the OA workflow.)

Additionally, for the DOI automerger only:

- OK to merge if both publications are from the following list: ['Academic Journal Article', 'In-house Journal Article', 'Professional Journal Article', 'Trade Journal Article', 'Journal Article', 'Review Article', 'Chapter', 'Conference Proceeding', 'Encyclopedia/Dictionary Entry', 'Magazine/Trade Publication', 'Comment/Debate', 'Editorial', 'Letter', 'Paper']. The PT after the merge should be the one from Pure, or if both records are from AI, the one from the more recently updated publication.
