### ISSUE TITLE
Add title fuzzy match requirement to AI-Pure automerger

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/researcher-metadata#534]
The `auto_merge` method in DuplicatePublicationGroup should query the group with the same fuzzy title matching logic as the grouping method to check if the two publications in the group match.  If so, allow the merge.  Otherwise, do not merge.

Should be done before #531

**Comment by Smullz622** [comment]
Found bug in tests, nil duplicate groups are matching and giving false positives
