### ISSUE TITLE
Pure importer bringing in publications more than once?

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#545]
I'm looking at duplicate groups and have noticed a few pairs of publications that are identical 
(in one case differing by a diacritical mark), where both records came from Pure. I've merged a couple before realizing the extent of this, but here are non-merged examples:

- 437117 and 436090
- 436391 and 436808
- 379796 and 509972
- 373138 (this pub has AI and Pure imports associated with it already) and 510022
- 510036 and 376894 (this pub has AI and Pure imports associated with it already)

I'm not sure why the importer created a new publication the second time rather than updating the existing one. Could it be that Pure has different IDs for all of these, so RMD can't tell they are the same publication?

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Yes, judging by the Pure IDs for these they are separate records in Pure, so the importer creates them as separate records.  Looks like there's a good amount of these.  The changes we are working on right now with the automergers should clean a lot of this up.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl Sounds good; thanks!

**Comment by anaelizabethenriquez** [comment]
@ajkiessl I think we can close this, but since it's currently assigned to you I wanted to confirm.
