### ISSUE TITLE
Increase text color contrast on profile demo page for better accessibility

### ISSUE THREAD

**Issue by njnash** [psu-libraries/researcher-metadata#55]
Some of the text/background color combinations don't provide enough contrast meet accessibility requirements.

This should be done both in the rails app and on the static profile demo page.

Aha! Link: https://penn-state-university-libraries.aha.io/features/MDDB-4

**Comment by banukutlu** [comment]
@anaelizabethenriquez @ajkiessl I am changing the link color which is causing the accessibility contrast errors 

<img width="223" alt="Screen Shot 2022-08-25 at 1 11 27 PM" src="https://user-images.githubusercontent.com/6477867/186727932-64bc005c-465b-4733-aa55-f73ffe724f97.png">
<img width="186" alt="Screen Shot 2022-08-25 at 1 12 29 PM" src="https://user-images.githubusercontent.com/6477867/186728028-3f3a1f4b-3d41-4a1d-b101-c132068bb75a.png">

to the recommended PSU link color  `PA LINK`

<img width="218" alt="Screen Shot 2022-08-25 at 1 13 50 PM" src="https://user-images.githubusercontent.com/6477867/186728275-50230d14-ad1a-4843-8320-5c3122df462c.png">

Currently it looks like the below, first link has the hover color, second is regular, both have contrast errors:

<img width="778" alt="Screen Shot 2022-08-25 at 1 03 39 PM" src="https://user-images.githubusercontent.com/6477867/186726980-4289089f-feff-4096-8476-ed7cc5100647.png">

Changing it as below

<img width="737" alt="Screen Shot 2022-08-25 at 1 04 03 PM" src="https://user-images.githubusercontent.com/6477867/186727196-85728894-dd0f-42dd-91b0-ca88c033c578.png">

I wanted to check with you for the :hover color. PSU recommendation is as below, hover is basically same color. 

<img width="580" alt="Screen Shot 2022-08-25 at 12 36 55 PM" src="https://user-images.githubusercontent.com/6477867/186727356-9ce73a24-a660-4686-be02-69d996d0be94.png">

Any preferences for the hover color here, should I just go with the same color as recommended or choose another color from the PSU palette that would work for accesibility.

**Comment by anaelizabethenriquez** [comment]
@banukutlu I have a slight preference to have a distinct hover color -- seems like that would be good for usability.

**Comment by ajkiessl** [comment]
I agree with Ana to go with a more noticeable hover color.

**Comment by banukutlu** [comment]
@anaelizabethenriquez @anaelizabethenriquez  Using visited link color for hover here:

<img width="761" alt="Screen Shot 2022-08-25 at 4 34 08 PM" src="https://user-images.githubusercontent.com/6477867/186763630-dd0139d1-f744-415c-a157-b065fb376d39.png">
<img width="788" alt="Screen Shot 2022-08-25 at 4 34 21 PM" src="https://user-images.githubusercontent.com/6477867/186763632-0f0add16-967e-4cc0-b408-de635d3985fa.png">

Would this work? Any thoughts?

**Comment by anaelizabethenriquez** [comment]
@banukutlu Works for me if it seems appropriate to you. Tagging Alex since you tagged me twice above -- @ajkiessl

**Comment by ajkiessl** [comment]
Works for me as well.
