### ISSUE TITLE
Fix URL in proxy notification email on stage

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#579]
The email that Stage sends to newly-designated proxies has a typo in the URL that points the new proxy back to the proxies page to confirm the link. This should be fixed. We should also check that the mailers on production are sending the correct link.

Edit: This may be a problem with all the mailers on Stage. The mailer for "RMD Authorship Claim" also gives the URL stem "https://stage.metadata.libraries.psu.edu" (correct stem would be "https://metadata-stage.libraries.psu.edu/").

**Comment by ajkiessl** [comment]
This is fine on QA and production.  The config/environments/beta.rb needs the stage host changed for `default_url_options`.
