### ISSUE TITLE
Duplicates with matching titles and DOIs failed to merge

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#582]
I was looking through RMD to think about whether we can turn the automatic emails back on, and I found a duplicate group that I think should have merged automatically: https://metadata.libraries.psu.edu/admin/duplicate_publication_group/130481

@ajkiessl is this just due to timing (maybe it's going to merge and hasn't yet)? If so, I'm curious whether we'd expect auto-mergeable but not merged items at the top of the duplicate group list all the time, or if that's temporary as the new code does its thing. If they'll always be at the top of the list, people doing manual deduplication should probably start elsewhere.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez These aren't being merged because of a bug.  I should be able to get this fixed today.  

Newly formed groups will show up at the top of the list, so yes, it would probably be better to start further into the list when manually deduping.

**Comment by anaelizabethenriquez** [comment]
Thanks, @ajkiessl !

I'll let Lucretia know about starting deduplication in the middle of the list. Tagging @nmg110 so she's also aware.
