### ISSUE TITLE
RMD admins can see a list of incoming publications that failed DOI verification or do not have a DOI

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/researcher-metadata#628]
The first step in the new open access deposit workflow in RMD will involve the verification of DOIs for incoming publications from Activity Insight that have associated file uploads. RMD will first attempt to [verify a DOI automatically](https://github.com/psu-libraries/researcher-metadata/issues/626), but if a DOI does not pass this automated verification, or if no DOI has been provided, then an RMD admin will need to try to either verify the provided DOI manually or find the missing DOI.

From the [dashboard page](https://github.com/psu-libraries/researcher-metadata/issues/627) for the new open access deposit workflow, RMD admins will be able to navigate to a list of publications that have associated file uploads in Activity Insight and that either do not have a DOI or do have a DOI and also have a flag indicating that the automated DOI verification failed. This will serve as a to-do list for manual DOI verification.

For now, each row in this list/table can just contain the title of the publication, the DOI (if present), and the DOI verification status.

**Comment by EricDurante** [comment]
Given how we're now planning to orchestrate this workflow, this is the first spot where I think we could choose to either implement a custom UI for doing manual DOI verification right in the list, or we could simply link to the existing rails_admin edit page for each publication in the list and add the DOI verification checkbox to that edit page.

Should we just do the easiest thing for now and then possibly make a second pass to improve the UI in the future?

**Comment by ajkiessl** [comment]
Yeah, I think we do the easiest thing first.
