### ISSUE TITLE
RMD admins can manually add/confirm a DOI for incoming publications

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/researcher-metadata#629]
For each publication that ends up in the [manual DOI verification list](https://github.com/psu-libraries/researcher-metadata/issues/628), RMD admins will need to be able to take one of the following actions:

1. If the DOI from Activity insight is actually correct despite failing automatic verification, then the admin will simply need to be able to manually flag the DOI as confirmed.
2. If the DOI from Activity insight is not correct, then the admin will need to be able to update the publication with the correct DOI and flag it as confirmed.
3. If no DOI was imported from Activity Insight, but a DOI for the publication does exist, then the admin will need to be able to enter and confirm the DOI.
4. If the publication has no DOI, then the admin will need to be able to leave the DOI field blank and still flag it as confirmed to indicate that a DOI does not exist.

In each case above, one result of the action is that the DOI is flagged as confirmed. In addition to saving the state of this flag, taking any of these actions will need to kick off the next automated step in the workflow. This may result in enqueueing the same kind of background job that that gets created as a result of a successful  [automatic DOI verification](https://github.com/psu-libraries/researcher-metadata/issues/626).

The existing RMD admin UI already provides a decent way to do data entry (such as adding or updating a DOI), so we may be able to leverage that to some extent for this and future issues. Or, it may make more sense to for us to create a custom UI to do the data entry from the list (which we'll ultimately want to do regardless). In either case, after the correct DOI has been saved, the admin will need to be able to take a custom action from the list that will confirm the DOI and kick off the next step in the workflow.

**Comment by ajkiessl** [comment]
To make this as simple as possible on the first pass, we will link to the record in the rails_admin to be edited.  We can plan to make a more user friendly custom UI in the future.
