### ISSUE TITLE
Database load script

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/researcher-metadata#662]
We have a rake task https://github.com/psu-libraries/researcher-metadata/blob/main/lib/tasks/database_data.rake that pulls production data to local envs and allows the programmer to uplaod this data to their local env or staging envs.  This will no longer work with the k8s setup.  Consider changing this to use port-forwarding and/or some kubectl commands to grab the data and upload it to local + staging envs.

**Comment by whereismyjetpack** [comment]
I'm going to work on a way to get the database dumped into qa / preview deployments, my current plan is to use s3 as a storage place for the database dumps, and give the deployments the ability to pull these dumps down and import on a developer action

**Comment by ajkiessl** [comment]
This is done
