### ISSUE TITLE
RMD admins can see a list of incoming publications that have possible duplicate metadata

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/researcher-metadata#677]
For publications entering the new OA deposit workflow with possible duplicate metadata that cannot be resolved automatically via https://github.com/psu-libraries/researcher-metadata/issues/630, deduplication will need to be performed by an RMD admin before the publication can continue in the workflow. From the dashboard page for the new workflow, we'll link to a list of the publications imported from Activity Insight with file uploads that still have potential duplicate metadata (that is, any such publications that still belong to a duplicate publication group). This will serve as a to-do list of manual work that needs to be done to move these publications through the deduplication step of the workflow.

**Comment by ajkiessl** [comment]
We are not concerning ourselves with deduplication for this workflow.  Closing this issue.
