### ISSUE TITLE
Increase frequency of automatic deduplication jobs

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/researcher-metadata#681]
Originally we thought that we'd include a deduplication step in the new open access deposit workflow (previously described in https://github.com/psu-libraries/researcher-metadata/issues/630), but we've determined that it won't really be necessary if we simply increase the frequency with which we're already running automated deduplication tasks.

Since possible duplicate publications are already being grouped as they're being imported, and since the first step in this workflow is to find and confirm a DOI for each incoming publication, merging with other duplicate publications that have matching DOIs can happen automatically in the background. It should be fine if automatic merging occurs when the publication is at any given stage in the workflow, but ideally we'd want merging to happen as soon as possible. So we should run the automatic deduplication tasks as frequently as is practical. At least for now we aren't going to worry about possible duplicates that don't match well enough to be automatically merged.

One of our main concerns regarding duplicate metadata in this workflow is the duplication of effort resulting from two coauthors of the same publication each entering the publication into Activity Insight and uploading a file. When that happens, both publications will enter into this workflow, but if auto-merging occurs frequently enough, then any duplicates that enter after the original should either quickly drop out (that is, be auto-merged into the original and deleted) after their DOIs have been confirmed, or the original and its metadata (and thus its stage in the workflow) will be merged into the incoming duplicate.

**Comment by ajkiessl** [comment]
@EricDurante You may not be able to see the pull request for this: https://github.com/psu-libraries/researcher-metadata/issues/681 .  I increased the frequency of the auto mergers to run daily, since that's about the frequency of our most frequent importers.
