### ISSUE TITLE
Automatically fetch open access status/info for incoming publications with confirmed DOI

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/researcher-metadata#686]
We already have cron jobs that import open access metadata from Open Access Button and Unpaywall for all of the publications in RMD on a regular basis. However, these jobs take a long time to run, and they run relatively infrequently. For the small subset of publications that will be entering this workflow, we want to fetch this information much more quickly at the outset so that the publications can proceed through the workflow as rapidly as possible.

So, when the main cron job that orchestrates this workflow finds a publication with a file upload from Activity Insight and a confirmed DOI but no open access metadata, it should enqueue a background job to fetch the open access metadata from Open Access Button and/or Unpaywall based on the DOI. We should do any refactoring that is necessary to share as much code as possible between this background job and the existing OAB and Unpaywall importers.

Just before enqueueing the job, we'll need to change the open access workflow status of the publication to indicate that this automated step is pending. This will require us to add a new value to the list of possible values for a publication's open access workflow status and then to filter out publications with that status when enqueuing jobs for this step. If the job completes successfully and records open access metadata, then we can clear this status as the last step.

If the automated search for open access metadata fails (i.e. because OAB and Unpaywall respond with a 404 given a publication's DOI), then we'll need to be able to set another new open access workflow status on the publication to indicate that an RMD admin needs to do a manual check for open access information for the publication.

**Comment by EricDurante** [comment]
There are some items for discussion here, and then I'll update/complete the issue description accordingly.

1. I made an assumption in this issue description which is that there's actually some other way for an RMD admin to potentially find open access metadata for a publication other than by checking OAB and Unpaywall (which we'll already be doing automatically). If there's not, then maybe no manual work will ever be required for this step at all.
2. Just as we now have a way to indicate that we have not yet attempted to verify a publication's DOI (flag is null), a way to indicate that we attempted to do it automatically and failed - thus requiring manual verification (flag is false), and a way to indicate that we have successfully verified the DOI (flag is true), I think that we're going to need some way to indicate these same states for the process of checking open access metadata. This will probably also be true for other metadata in later steps in the workflow. Total absence of any open access metadata could indicate that we've not yet checked. However, if we run the automated check and find no open access metadata, then we'll need a way to indicate this state so that a new job isn't queued up to check again. Since we'll be setting the open access workflow status to indicate that manual intervention is required, we could use that to indicate this state. Likewise, if the manual check also turns up no open access info, then we'll need a separate way for the admin to indicate this state (equivalent to setting the DOI confirmed flag to `true` with no DOI) so that the publication doesn't end up back in line for automated OA info search.

**Comment by ajkiessl** [comment]
I guess an admin could check Scholarsphere, but we could do that automatically.  Other than that, there's the chance that the publication is in the Law School repository and either hasn't been merged with this, or hasn't been imported yet (_and_ hasn't been picked up by Unpaywall or OAB).  I'm starting to think that maybe this step should just be an automatic step and have no manual stop.

I'm curious how this works with the current workflow.  @nmg110 Do you or Ana ever manually search for open access locations for publications in this workflow?  Specifically in places other than Unpaywall, OAB, or Scholarsphere?

**Comment by ajkiessl** [comment]
We won't need a manual step here.
