### ISSUE TITLE
"Bucket" and list for publications that need manual file version checking

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/researcher-metadata#688]
We'll need another card on the main OA Workfow dashboard that describes the manual file version checking step and has the number of publications in the bucket in the top right corner.  This card should also be a link to a list of publications that need manual file version checking.  

We don't currently have a field to store file version on the `ActivityInsightOaFile` model, so that will need to be added.  This should be restricted to published and accepted versions kind of like how we do it in `OabPermissionsService`.  We'll need a scope to select the publications that will be in this bucket.  We'll also need another status added to the `oa_workflow_statuses` that this scope will use to select publications for this bucket. 

The list should have the title of the publication the file belongs to, and the file location.

**Comment by ajkiessl** [comment]
This step should just be for publications that we could not determine the version for.  Looks like it's going to be version == 'unkown'.  We'll have another step for when the version is the wrong version.

**Comment by EricDurante** [comment]
@ajkiessl This sounds like a list of the files that need manual version checking rather than a list of publications - which makes sense to me. Is that what you were thinking?

**Comment by ajkiessl** [comment]
@EricDurante Sort of, yes, but I don't want to present any files to admins whose associated publication has another file whose version could be determined.  So the list will display publications whose file versions are _all_ 'unknown', and list all those files in the row.  The editing portion will only be done on the file, though.

**Comment by EricDurante** [comment]
@ajkiessl Great - that mostly makes sense to me, but I was wondering about what happens if we have a publication with several files (either because multiple authors uploaded a file and the publications were merged, or because someone replaced their original upload) and we've figured out the version for one file, but then after the permissions check we find out that it's not the version that we need. In that case, aren't we going to want to check the versions of the other files to see if one of them is the correct version?

We definitely don't need to show anything in this list for a publication that has at least one file with a known version _and_ deposit permissions for that version. In fact, once we hit that condition, we can stop all other version and permissions checking for that publication's files.

**Comment by ajkiessl** [comment]
@EricDurante Hmm yeah good point we'll want to determine any other 'unknowns' if the known version we have is the wrong version.  We could just leave that to be handled at the manual stop that happens after the permissions check, or I could try to add something to the scope that checks if the preferred_version is not nil, and the known versions do not match that preferred version, _and_ there's still an unknown version, to show that in this list.

**Comment by EricDurante** [comment]
Yeah, I know that this situation will happen sometimes, but I don't know how often. So maybe it's reasonable to leave it to be sorted out at the last step (assuming that we can come up with a UI for doing it that isn't too confusing)? It feels like it would fit better here though, and I think we'll have to figure out how to find those publications/files either way.

I was picturing the final, manual step as a list of publications that have a file that we know can be deposited. That list could show all of the metadata that's going to be sent to Scholarsphere and highlight any publications with missing/invalid metadata. Each row in the list could have a "Deposit" button (only if the metadata is valid) to send the file and metadata to Scholarsphere, and an "Edit" link that goes to the Rails Admin edit page for the publication to fix bad/missing metadata. I know that there will be cases where admins will want to edit metadata that is technically valid prior to submission (i.e. fixing text formatting/markup in abstracts). So this way an admin could review the metadata for every publication before submission and easily find and fix obvious metadata issues. 

In any case, I think we'll want the _automated_ version checking to process every file that belongs to a publication that doesn't already have a file with known version and permissions that can be deposited.

**Comment by ajkiessl** [comment]
I think it makes sense to include in this list publications that have a known version, but not the right version, _and_ have another file (or files) that is unknown.  I will try to incorporate that into the scope.

I was thinking we'd have another list/bucket for publications that we know all the versions for, but they are the wrong version.  That was the manual stop I was referring to above that we could potentially have these sorted out in, but I guess we haven't fully determined what we want to do with those types of publications.  

I've kind of been thinking about this wrong, though.  I was assuming the permissions step had to happen after the version checking step, but that's not true.  We can bundle together publications whose files are all 'unknown' or not-the-correct-version with at least one file that is still 'unknown', in this list.  Publications whose versions are know, but they are not the correct version will be handled separately.
