### ISSUE TITLE
Download publication files from Activity Insight

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/researcher-metadata#691]
After a publication that is moving through the Activity Insight open access workflow has had its DOI confirmed and its open access status checked, the next step will be check to see what version of the publication was uploaded. In order to do this, we'll have to actually download and store a local copy of the file that was uploaded to Activity Insight by the faculty member so that we can analyze the file with our existing (and currently in development) version checking tools (https://github.com/psu-libraries/researcher-metadata/issues/575), and so that an RMD admin can view the file if the automated version checking is inconclusive.

Like the other steps in the workflow, this step will begin with the overall workflow cron job queuing up a background job to handle the file download. The cron job should look for publications that have an Activity Insight file upload location, a confirmed DOI, and open access metadata that indicates that the publication should be deposited in Scholarsphere if possible. At this point, we'll be looking for publications that have successfully gone through the automated open access metadata check from the previous step and still do not have any associated open access locations. We'll also need to filter out publications with files that have already been downloaded and publications that already have pending download job on the queue.

Once a file has been downloaded, we may ultimately want to do the version checking  as part of the same step (background job), or we may find that it makes more sense for the version checking process to be handled by a separate job, but for the purposes of this issue, we'll consider it complete whenever the files are being downloaded.

As for the mechanics of actually downloading the files, we may be able to incorporate code from the [fams_tools](https://github.com/psu-libraries/fams_tools) repository (which has similar functionality) with the ultimate goal being to deprecate and eventually discontinue use of fams_tools for this purpose.

**Comment by EricDurante** [comment]
@ajkiessl Do you think this one makes sense? Anything to add?

**Comment by ajkiessl** [comment]
Yeah this sounds good.  We'll need to set up an API key in the ai-s3-authorizer.  The request used to get the files in fams_tools is here: https://github.com/psu-libraries/fams_tools/blob/main/app/models/post_print_analyzer.rb#L22-L30 .

**Comment by ajkiessl** [comment]
We'll want to implement the file version check here.  So, if the code for version checking is done before this issue is complete, it should be incorporated with this issue.

**Comment by Smullz622** [comment]
@ajkiessl When Eric & I were mapping this out, we were debating about whether version checking should be a separate issue/job. The concern was what would happen if anything went wrong. For example, if the file is downloaded and an error occurs during version checking, retrying the job would download the file again. It seems like there would be benefits to separating the two processes. Thoughts?
