### ISSUE TITLE
List publications that are ready for manual metadata review prior to Scholarsphere deposit

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/researcher-metadata#715]
~~Once a publication has a file with a known version that we've confirmed can be deposited into Scholarsphere, we'll want to automatically check to see if the publication has all of the metadata this is required by Scholarsphere. If it doesn't, then an RMD admin will need to add or correct metadata until it's valid. However, even if the publication passes automatic validation of the metadata, an RMD admin should still review the metadata that will be sent to Scholarsphere to ensure that it actually makes sense, is formatted appropriately, etc.~~

~~So the final step in this workflow will always be manual for now, and it should consist of a list of publications that have a file that we know can be deposited. Each row in this list should show all of the metadata that's going to be sent to Scholarsphere for the given publication, and publications with missing/invalid metadata should be highlighted in some way. Each row in the list should also show a link to view/download the file that is going to be selected to be sent to Scholarsphere.~~

~~If a publication's Scholarsphere metadata is all valid, then its row in the list could include a "Deposit" button (to be implemented in a separate issue) that would send the file and metadata to Scholarsphere and update the publication's open access status/locations in RMD. If a publication's Scholarsphere metadata is not completely valid, then we could highlight the row and not display the "Deposit" button. We might also consider grouping valid and invalid publications separately in the list or even have two separate lists on the same page. In either case - valid or invalid - we should also show a link to edit the publication's metadata in the Rails Admin UI.~~

☝️The above was my initial guess at how this last step should work, but we now have a better understanding of how admins will manage this list, so we're going to do this a bit differently.

This list will still show only publications which have a file that can be deposited, but in each row of the list we'll only need to show the PSU user ID of the person who added the publication to Activity Insight, the publication's title, and the date when the most recent file for the publication was imported from Activity Insight. The list should be in order by that date so that the publications with the files that have been around the longest are at the top of the list to be worked on first.

The publication title will be a link to a detailed view of all of the publication metadata that is going to be sent to Scholarsphere along with the file. Here an admin will be able to see if any metadata is missing or incorrect prior to deposit. This page will also show a link to edit the publication metadata in the existing Rails Admin UI, and a button to deposit the file/metadata in ScholarSphere.

For now there's no need to visually indicate invalid (missing) metadata fields that are required for ScholarSphere deposit, but we should probably only display/enable the "deposit" button if all of the required metadata is present. This will hopefully prevent us from needing to handle the error condition where ScholarSphere rejects a deposit because an admin accidentally submitted incomplete metadata.

The metadata detail page should show the following information about the publication:

- title
- subtitle (if any)
- description/abstract
- DOI
- publication date
- journal title
- rights/license
- embargo date (if any)
- set statement (if any)
- a list of the names of the publication's creators/authors
- the user who will be listed as the depositor in ScholarSphere (the current RMD admin)
- a link to download the file that will be deposited

**Comment by EricDurante** [comment]
@anaelizabethenriquez @ajkiessl

I updated the description of this issue after talking it over with Ana. Please have a look and verify that I got everything right and that it all makes sense.

In particular, I wasn't sure who the depositor should be in ScholarSphere in this case. I assumed that it should be the RMD admin who is reviewing the metadata and actually making the deposit - is that correct?

Also, I'm not sure that we currently have a way of knowing for certain which Activity Insight user uploaded a file (other than maybe parsing that info out of the file location string/path, which would be less than ideal). All that we would know would be the list of the publication's PSU authors, and there may be more than one if the publication has been merged with other imports. So I'm thinking that we may need to add a field to `ActivityInsightOAFile` to record the PSU user ID (or RMD user ID) of the person who added the file to Activity Insight whenever we import the file metadata (or something like that). Does that sound right? Or am I missing/forgetting something?

**Comment by anaelizabethenriquez** [comment]
Thanks, @EricDurante 

> So I'm thinking that we may need to add a field to ActivityInsightOAFile to record the PSU user ID (or RMD user ID) of the person who added the file to Activity Insight whenever we import the file metadata (or something like that). Does that sound right?

Yes, that sounds right to me.

> In particular, I wasn't sure who the depositor should be in ScholarSphere in this case. I assumed that it should be the RMD admin who is reviewing the metadata and actually making the deposit - is that correct?

Actually, I think we want the depositor in ScholarSphere to be the person who added the file to Activity Insight. My understanding is that the "depositor" is the person who will have regular privileges to update the file later on. It's important for one of the authors (ideally the person who provided the file) to have those privileges. There will always be Libraries folks who have admin privileges in ScholarSphere, and that's what we'd use if we needed to revise the deposit. But we also want "breadcrumbs" (see #765 ) so we can learn more about how the deposit actually happened. One useful breadcrumb that's in place right now and should be preserved is in the public version info in ScholarSphere, where edits are signed by the user who made them (e.g. [this deposit signed by RMD](https://scholarsphere.psu.edu/resources/9f38bf47-9b24-46cc-b586-1bdc57de54b2)). Anything deposited through the AI OA Workflow should be signed by RMD. In #765 we'll work on parsing that out further, I hope.

**Comment by EricDurante** [comment]
> Actually, I think we want the depositor in ScholarSphere to be the person who added the file to Activity Insight.

Ah - so another, even more important reason for needing to know the AI user who added the file. Does adding some sort of user ID field to `ActivityInsightOAFile` sound like a good way to handle this to you, @ajkiessl? I guess we might as well make it a proper foreign key and use the RMD User ID. Somehow we'd need to backfill that information in production for files that have already been imported too...

**Comment by ajkiessl** [comment]
@EricDurante Yeah, that sounds good.  We could write a script to backfill that data.  

We often have proxies managing data for faculty in Activity Insight.  There's the chance an OA file was uploaded by the proxy and not the RMD User.  Not sure if this is important/helpful, or if there's any way to identify who the proxy is.  I can see if the API response gives us any information on the proxy.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Ah okay that sounds good.  I couldn't find any way to determine the proxy through the API either, so we can ignore that.

**Comment by EricDurante** [comment]
😅 whew

**Comment by EricDurante** [comment]
Ok - thanks, @anaelizabethenriquez. So we'll pick a file at random if there is more than one, and the RMD admin will be able to see the file that was randomly chosen prior to deposit. If they absolutely need one of the other files to be deposited instead, then I think that there will be a way to work around this. For example, they could manually change the version on the chosen file to be one that isn't acceptable for deposit. That would be incorrect of course, but it would cause RMD to choose a different file for deposit, and I don't think that it would have any other consequences.
