### ISSUE TITLE
List for Publications whose file versions are all determined but the wrong version

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/researcher-metadata#719]
We'll want to keep these in their own list separate from #688.  At this point in the workflow there's the chance the author will need to re-upload a file with the proper version.  We haven't entirely figured out how this will happen and what automation we can do with it (#692), but we do know that we want the admins to have a list to view these publications and their files.  The list should probably include the publication's title, its preferred version, the file locations (with a link to view the file or edit the file record), and the version of each file.  We'll also want a link to edit the publication in case an admin wants to view other metadata for the publication or change some metadata.

**Comment by ajkiessl** [comment]
Take a look here for more details on how we want to implement this list: https://github.com/psu-libraries/researcher-metadata/issues/692#issuecomment-1679413809

**Comment by anaelizabethenriquez** [comment]
@ajkiessl I am getting error messages right now if I click the "Send email" button for [this list](https://metadata-qa.libraries.psu.edu/activity_insight_oa_workflow/wrong_file_version_review) on QA. "Send batch email" does not give an error.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez This will be fixed in #841
