### ISSUE TITLE
Update the "front page" of RMD

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#747]
Update metadata.libraries.psu.edu/ with the following text changes:

Change "Purpose":

- Current text: "Our goal is to provide centralized, consistent access to up-to-date metadata for Penn State faculty research."
- New text: "Our goal is to provide centralized, consistent access to up-to-date metadata for Penn State research and support researchers in depositing publications in ScholarSphere under [Penn State's open access policy](https://openaccess.psu.edu/)."
- Note: I'm deliberately mentioning ScholarSphere (since we've gotten feedback about that) but not linking to it (since we want depositors to use the RMD workflow for article deposits).

Change "Learn More" link:

- Current link: mailto:L-FAMS@lists.psu.edu?Subject=RMD%20Inquiry
- New link: https://github.com/psu-libraries/researcher-metadata/wiki
- Note: This is the short term solution. In the long term, we'll replace this with #859.
- #860 blocks this.

Change "Build Faculty Profiles" and related text (blocked by #861 ):

- Current text: "Build Faculty Profiles"
- New text: "Build Profiles"
- Current text: "Building profile pages for your college's faculty directory? Allow us to do the heavy lifting for you by leveraging our freely available Faculty profile template that displays metadata from our API. "
- New text: "Building profile pages for your unit's directory? Creating a list of publications from your unit? Leverage our freely available profile template that displays metadata from our API, or check out our demo unit publication list."

Background on feedback that we're trying to address with these edits (not sure that these changes help with 4 or the second part of 3):

1. Include a link to openaccess.psu.edu/ and information about open access and deposit to ScholarSphere
2. Consider how this connects to ScholarSphere and what we want to promote (profiles, OA workflow, etc.)
3. Update language so we're saying "researchers" rather than "faculty," but be open about our lack of metadata for many non-faculty researchers
4. Make it clear in the public info about RMD is that it isn't comprehensive. I think we're pretty good about saying this and listing Activity Insight and Pure as data sources, but we should be careful on this point.

**Comment by LHillColes** [comment]
Include link to FAQ Penn State Libraries about open access publications, especially what versions to upload to their profiles (final vs. accepted version manuscript). Possibly change wording "faculty profiles" (since non-faculty can upload documents, such as student researchers).

**Comment by anaelizabethenriquez** [comment]
Related to #774 we should emphasize how easy it is to use the data for faculty profiles (and for listing a unit's publications).

**Comment by anaelizabethenriquez** [comment]
@bdezray @nmg110 @binkylush Can you take a look at the text changes for the RMD homepage mentioned in this issue description, and let me know if you have any other changes to suggest? Thanks!

**Comment by nmg110** [comment]
I think it looks good. I did make some changes to the Wiki page, anytime Digital Measures was mentioned I changed the wording to Activity Insight, I would rather use "AI" than "DM".  :-) 

Change "Build Faculty Profiles" and related text - I am not so sure about changing the word Faculty to Researchers. Because both teaching faculty and research faculty are in RMD, correct? I think we should keep the wording as is otherwise, teaching faculty may complain and want to know why is their information not available. Just a thought.

**Comment by anaelizabethenriquez** [comment]
Thanks, @nmg110 !

> Change "Build Faculty Profiles" and related text - I am not so sure about changing the word Faculty to Researchers. Because both teaching faculty and research faculty are in RMD, correct?

That is a good point, that someone with a title like "Associate Teaching Professor" might not think they are included in "researchers" (whereas they certainly are included in "faculty"). I was thinking that "researchers" is more inclusive and more accurate because it describes everyone who could have an RMD account (including grad students, staff, Associate Teaching Professors, Associate Research Professors, Associate Professors, and other faculty). 

Of course, as you know, our current data sources mean that "you could have an RMD account" is a much bigger group than "RMD has good data for you". I just did a quick check with the math faculty at UP, and it looks like professors with "Research" or "Teaching" in their titles are not in Pure. I assume they do use Activity Insight, but RMD data is still going to be less than ideal both for "Research" and "Teaching" faculty.

**Comment by anaelizabethenriquez** [comment]
I've changed the planned text above to just "Build Profiles"

**Comment by bdezray** [comment]
Looks good to me! My only thought is in the purpose statement the term publication is used which I think is fine, however if we wanted it to match the current work type option in ScholarSphere that I think is most often deposited by RMD it should be changed to article.
