### ISSUE TITLE
Login errors

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#749]
A user has reported, and I have replicated, a login error for RMD. I visited metadata.libraries.psu.edu and clicked the "Sign In" link. I got the following error in a pink banner at the top of the page: "There was an error while attempting to log in to your account. Please contact RMD support for assistance."

Can you tell what's going on, @ajkiessl ?

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Looks like the Azure login client secret keys expired.  I'll get these updated ASAP.

**Comment by ajkiessl** [comment]
Update:  The Azure keys were updated in the repo, but chef was not running on the production server.  We manually updated the configs to get this working for now.  We still need to get chef working properly.

@anaelizabethenriquez Users should now be able to log in.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl Thanks!

**Comment by ajkiessl** [comment]
@whereismyjetpack Were we able to get chef running properly again?

**Comment by whereismyjetpack** [comment]
Apologies for the delay. Chef ran this morning on rmd, and this should be good to close.
