### ISSUE TITLE
RMD not sending full number of OA reminder emails

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#764]
We've just noticed that RMD is not sending the full number of OA reminder emails, despite there being plenty of users who need them. (In "Organizations," I currently see 664 users in "Pennsylvania State University" need a reminder email.) Here's what I see:

May 21, 2023 00:00 to May 28, 2023 00:00: 50 (Equal to cap setting at that time)
May 28, 2023 00:00 to June 04, 2023 00:00: 200 (Equal to cap setting at that time)
June 4, 2023 00:00 to June 11, 2023 00:00: 54
June 11, 2023 00:00 to June 18, 2023 00:00: 75 (Possibly equal to cap setting at that time)
June 18, 2023 00:00 to June 25, 2023 00:00: 182
June 25, 2023 00:00 to July 02, 2023 00:00: 137
July 02, 2023 00:00 to July 09, 2023 00:00: 45
July 09, 2023 00:00 to July 16, 2023 00:00: 46

I'm not certain what the cap was set at for the first few weeks above, but it has been at 200 since June 15. (I just changed it to 100 this morning when I noticed this issue.) If it was lower, it would still have been a round number. Any idea what's going on here?

**Comment by ajkiessl** [comment]
@anaelizabethenriquez I'm not 100% sure what could be causing this, but I have a theory.  I did test sending 200 emails locally (with mailers turned off so it didn't actually send the emails) a few times and it seemed to work properly.  There's always the chance that the number of users that need an email is fluctuating with imports.  Perhaps there was a large amount of open access publications imported in the last week?  When the "new" OAB and Unpaywall imports happen right before the emails go out, that number could then drop dramatically.  If that number then drops below 100, it may only send 46 (or any of those numbers above that are below the threshold).

I'm curious how you are getting the numbers you listed above?

**Comment by anaelizabethenriquez** [comment]
Thanks, @ajkiessl ! I got these numbers on the [Users page](https://metadata.libraries.psu.edu/admin/user), with filters set for "Open access notification sent at" "Between" and then the timestamps listed.

Does your explanation work even though there are lots of users (currently 575) in the organization ["Pennsylvania State University"](https://metadata.libraries.psu.edu/admin/organization/22) who need reminder emails?

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Potentially, it looks like this Monday when the number was up to 600+ users needing emails, we had exactly 100 go out: https://metadata.libraries.psu.edu/admin/user?model_name=user&f%5Bopen_access_notification_sent_at%5D%5B01141%5D%5Bo%5D=between&f%5Bopen_access_notification_sent_at%5D%5B01141%5D%5Bv%5D%5B%5D=&f%5Bopen_access_notification_sent_at%5D%5B01141%5D%5Bv%5D%5B%5D=July%2016%2C%202023%2009%3A35&f%5Bopen_access_notification_sent_at%5D%5B01141%5D%5Bv%5D%5B%5D=July%2019%2C%202023%2009%3A35&query= .  

This is a good sign.  If we continue to get the correct numbers over the next couple weeks, I think we could pretty decently assume that there was a sudden influx of open access publications that got us up to 600, and before that, there were just so few users needing emails that only 46, 45, etc. were being sent out.

Another thing I hadn't considered is that a bunch of users could have reached the 6 month limit to not send them another email right before we had the sudden influx.  That could be another reason why we bounced from 46 to 664.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Looks like we had 100 emails go out again: https://metadata.libraries.psu.edu/admin/user?model_name=user&f%5Bopen_access_notification_sent_at%5D%5B89928%5D%5Bo%5D=between&f%5Bopen_access_notification_sent_at%5D%5B89928%5D%5Bv%5D%5B%5D=&f%5Bopen_access_notification_sent_at%5D%5B89928%5D%5Bv%5D%5B%5D=July%2023%2C%202023%2010%3A29&f%5Bopen_access_notification_sent_at%5D%5B89928%5D%5Bv%5D%5B%5D=July%2025%2C%202023%2010%3A29&query= .

I'm going to close this issue.  I believe we just had a low number of users needing emails, so the correct number of emails wasn't being sent.
