### ISSUE TITLE
When a work is withdrawn or deleted in ScholarSphere, remove the Open Access Link in RMD

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#766]
Edited to include ScholarSphere's options for "withdrawn" and "deleted" works:

When a work is withdrawn or deleted in ScholarSphere, remove the Open Access Link in RMD. We'd like to remove Open Access Links with the source "ScholarSphere" if the work is withdrawn or deleted in ScholarSphere. This should apply to works deposited using the RMD OA workflow as well as works deposited directly in ScholarSphere.

There are also Open Access Links pointing to ScholarSphere that have OA Button or Unpaywall as the source. I don't think we don't need to remove these. OAB and Unpaywall should be removing them from their databases automatically, and the regular imports should pick that up. Right?

**Comment by EricDurante** [comment]
Probably the ideal way to achieve this would be to implement webhooks for these events in ScholarSphere. They wouldn't necessarily need to be able to handle really generalized use cases (unless we foresee other potential use cases for webhooks). So the implementation could be fairly simple and tailored to our one specific use case here.

Thoughts?

**Comment by ajkiessl** [comment]
@EricDurante That sounds good to me.  So on the RMD side we'd need an API endpoint for deleting Open Access Locations?  It would likely accept the ScholarSphere URL as payload to identify the record to delete.

**Comment by EricDurante** [comment]
Yep, that's what I'm thinking. It would be a different API from the existing API in RMD (it wouldn't be public). For now (and maybe forever), it would only have one client - ScholarSphere, and only do one thing using a single endpoint. So authentication could be super simple - just one shared secret in the runtime configs, and the API itself could be as simple as possible.

**Comment by EricDurante** [comment]
While we're working on that, we can just ask the ScholarSphere team to implement the callback and HTTP request to RMD...

![](https://en.meming.world/images/en/thumb/1/17/Monkey_Puppet.jpg/300px-Monkey_Puppet.jpg)

**Comment by ajkiessl** [comment]
Oh no, not _them_.

**Comment by ajkiessl** [comment]
## WDDLL

- [ ] Endpoint for deleting open access locations.  This should accept a single ScholarSphere url to identify which OAL to delete.  We already have an `APIToken` model set up with a `write_access` attribute to fine-tune access controls, so we should be able to use this for authentication.  We don't need Swagger docs for this since we'll be using it internally.
- [ ] https://github.com/psu-libraries/scholarsphere/issues/1656
