### ISSUE TITLE
Upon deposit, send confirmation email to author from whose AI profile we got the file

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#796]
When there is a successful ScholarSphere deposit at the end of the AI OA workflow, RMD should send a confirmation email to the author from whose AI profile we got the file. This is the same person who should have the "depositor" role in ScholarSphere for the deposit.

RMD should not send the confirmation email that's currently sent at the end of the regular RMD ScholarSphere deposit workflow. This email should take the place of that one.

Here is the text for the email:
From: openaccess@psu.edu
Reply-to: openaccess@psu.edu
Subject: Publication deposited to ScholarSphere 

Hello, 

The following file, which you [uploaded in Activity Insight to be made available for public access](https://openaccess.psu.edu/deposit/activity-insight/), has been deposited for public access in ScholarSphere.

- [ScholarSphere link(s)] 

If you would like to update or correct the publication information in ScholarSphere, you may do so by logging in and clicking the “Create New Version” button on the publication page. 

If you have provided additional files in Activity Insight, we will follow up about those as soon as we can. If you have any questions, please contact us at openaccess@psu.edu. Thank you for making your research available to the public. 

Sincerely,

Office of Scholarly Communications and Copyright
Penn State University Libraries
openaccess@psu.edu

**Comment by ajkiessl** [comment]
Send request to Activity Insight to update the publication indicating that it has been "Deposited to Scholarsphere".
