### ISSUE TITLE
DOIs not automatically confirmed

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#803]
Looking at the publications that need DOI confirmation ([publications with "DOI verified" present but False](https://metadata.libraries.psu.edu/admin/publication?model_name=publication&f%5Bdoi_verified%5D%5B86248%5D%5Bv%5D=_present&f%5Bdoi_verified%5D%5B86329%5D%5Bv%5D=false&query=) -- don't know why this is a different number of pubs than in the workflow interface; I did that search so I could export the data), I'm seeing quite a few publications (43) where automated verification failed even though the title exactly matches the title from Crossref. CSV of those attached.

[Unconfirmed.csv](https://github.com/psu-libraries/researcher-metadata/files/12458133/Unconfirmed.csv)

Possibly the issue is that these articles have subtitles, with the subtitle appearing in the Secondary title field in RMD, as well as in the title field. But I'm still not sure why the DOI verification would fail, given the exact match between the two title fields.

This is not urgent to fix, but it would save a fair bit of manual labor.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl Tagging you so you'll see this.

**Comment by ajkiessl** [comment]
fixed in #807
