### ISSUE TITLE
Create a "troubleshooting" list in the AI OA workflow

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#806]
This list should be called "Troubleshooting" and should include all publications that are subject to the workflow (#797).  We should order this by creation date, so oldest things should be at the top. 

We will use this list for troubleshooting during development and during regular use of the workflow. If publications are ending up in this list, Ana or another admin will need to review them and get them back on track.

**Comment by Smullz622** [comment]
@anaelizabethenriquez I want to check on two things:

1) Our base scope is for oa pubs without a scholarsphere location. I'm guessing we also want to filter out gold/hybrid statuses?

2) What columns do you want on the table? Bare minimum would be pub title and created at date. My instinct is to also have a column related to each step (doi verified?, oa status, etc) so you can easily see where it's stuck. Also thinking file should link to the admin view of file vs download link. What do you think?

**Comment by anaelizabethenriquez** [comment]
>Our base scope is for oa pubs without a scholarsphere location. I'm guessing we also want to filter out gold/hybrid statuses?

Hmm. As part of #797 RMD is going to report to AI that those are "Already Openly Available", so we know those are taken care of. I think it makes sense to exclude them from troubleshooting. I am wondering if the right scope for the troubleshooting list is actually everything in AI that has a post-print status of "In Progress," but I'm not sure if we've made plans to update that field to "In Progress" upon import?

>What columns do you want on the table? Bare minimum would be pub title and created at date. My instinct is to also have a column related to each step (doi verified?, oa status, etc) so you can easily see where it's stuck. Also thinking file should link to the admin view of file vs download link. What do you think?

I think we can go with a small number of columns. Since this feature is essentially a failsafe, we shouldn't be working in it that often, and I'm anticipating that the troubleshooting work will mostly occur in the admin view screen for the publication. Let's do:

- Pub title (linking to admin view of publication record)
- Imported from AI at (Timestamp for each file -- if there's more than one file, we should order the publication in the list according to the most recent time stamp. That is, one super-old file shouldn't push the publication to the top of the list, if there are also new files. Does that make sense?)
- Filename(s) (linking to admin view of file)
