### ISSUE TITLE
Carrierwave leaves behind empty directories

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/researcher-metadata#824]
When performing a restore this morning, I noticed a bunch of empty directories in the uploads directory. This is due to carrierwave not removing the directory of a file when the file is removed. This seems to be a long standing issue, that can be resolved with an after_action. I like the solution proposed here 

https://github.com/carrierwaveuploader/carrierwave/issues/222

If we think this is sane work to do, I can get started on it

**Comment by EricDurante** [comment]
>This seems to be a long standing issue, that can be resolved with an after_action

Yeah, this looks like the [sanctioned way](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Make-a-fast-lookup-able-storage-directory-structure) to do it.

I'd say go ahead 👍

**Comment by ajkiessl** [comment]
This is fixed for Activity Insight OA Files: https://github.com/psu-libraries/researcher-metadata/blob/main/app/uploaders/activity_insight_file_uploader.rb#L5

It nstill needs to be done for ScholarSphere files (from the standard OA workflow)
