### ISSUE TITLE
OABPermissionsClient when there are no permissions

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/researcher-metadata#827]
```
Handler

    --- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper
    job_data:
      job_class: PermissionsCheckJob
      job_id: 7315683a-684a-47fd-a0a6-e12a33b0e3da
      provider_job_id: 
      queue_name: default
      priority: 
      arguments:
      - 392188
      executions: 0
      exception_executions: {}
      locale: en
      timezone: UTC
      enqueued_at: '2023-09-25T14:45:16Z'

Last Error

    undefined method `each' for nil:NilClass

        all_permissions.each do |perm|
                       ^^^^^...
```

`all_permissions` returns nil when it can't parse json from the `permissions_response` perhaps we need to wrap this in an `unless` or return an empty array in the PermissionsCheckJob?

**Comment by EricDurante** [comment]
This job class doesn't even exist in my current feature branch any more, but it looks like some form of the same issue still exists in the OABPermissionsClient class that has been updated in my branch. I think we should leave this issue open and investigate/probably fix after my branch is merged.

**Comment by whereismyjetpack** [comment]
Thanks for the update. I've updated the title, and will stand down
