### ISSUE TITLE
Version option for files determined to be neither the Accepted Version nor the Published Version

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#840]
Currently, the "Version" field has three possible values: "unknown", "acceptedVersion", and "publishedVersion". Sometimes, Activity Insight users upload files that are not article files. We should add another possible value to the "Version" field: "notArticleFile". 

Eventually, such files should connect to #839. For MVP, we just need a way for reviewers to assign these a version so they don't clog up the "Needs Version Review" list.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl tagging you so this doesn't catch you by surprise at stand up tomorrow.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl if we implement this issue, will the files with "version" of "notArticleFile" end up within scope for [Publications with Wrong File Version](https://metadata-qa.libraries.psu.edu/activity_insight_oa_workflow/wrong_file_version_review)? That might be OK if the emails make sense (and would make #839 moot), but if the email settings don't work with this new value, we'd want to exclude things with this value from the scope for that bucket.

**Comment by ajkiessl** [comment]
Yes, it does look like they would end up in that bucket, so I agree we should exclude them.  Also — for whoever works on this issue — when #715 is done, there will be a method for selecting the AI file to send to ScholarSphere (`#ai_file_for_deposit`).  We'll need to adjust some of the logic in there to filter these out.
