### ISSUE TITLE
Change name of column with link to file metadata on Publications Requiring Permissions Review on a File page

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#849]
On QA right now, the [Publications Requiring Permissions Review on a File page](https://metadata-qa.libraries.psu.edu/activity_insight_oa_workflow/permissions_review) is a list with two columns -- one column has the Publication title with a link to edit Publication metadata. The other has the filename(s) and version(s) with link(s) to edit file metadata.

Let's change the name of the file metadata column to "File metadata: Filename (Version)" to make it clearer what's in that column.

**Comment by Smullz622** [comment]
@anaelizabethenriquez [Preferred Version Review](https://metadata-qa.libraries.psu.edu/activity_insight_oa_workflow/preferred_version_review) has the same thing. I assume that one should be updated as well?

**Comment by anaelizabethenriquez** [comment]
@Smullz622 Yep! Thanks for catching that. Let's make the change there too.
