### ISSUE TITLE
"Become this user" leads to an error

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#917]
The step in the proxy process where the proxy "becomes" the primary user seems to be broken. We got an error report from a regular user (who has proxy status), and I'm getting the same error if I try to proxy as an admin.

I anticipate we won't be able to do anything until at least next week, and I told the user that.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez This has been fixed an deployed to production
