### ISSUE TITLE
Cannot deposit publication without a DOI from the last step of AI OA Workflow

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#933]
It doesn't seem to be possible to deposit a file from the last step in the AI OA Workflow if the publication does not have a DOI. If there is no DOI, "Insufficient metadata to upload to ScholarSphere" is displayed. I don't believe this is how we intended for this to work, but I'm also not sure that we tested this with a publication that doesn't have a DOI. 

Here is an example: https://metadata.libraries.psu.edu/activity_insight_oa_workflow/metadata_review/460659

For publications that have DOIs, we want to make sure that we find and include the DOI with the deposit. But some publications do not have DOIs at all, so if the "DOI verified?" Boolean is set to "True", we should be able to deposit even if the DOI field is blank.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Ah yes, I implemented it to require the DOI for submission.  This should be a quick fix.  I'll see if I can get it done before the end of the day.

**Comment by anaelizabethenriquez** [comment]
Thanks @ajkiessl ! Just used this in production, and it worked.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Ah good.  I was just about to message you.
