### ISSUE TITLE
User who is no longer affiliated with Penn State received reminder email

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#954]
On March 11, user 5146 received an OA reminder email. They responded to say that "I left Penn State couple of years ago." RMD indicates that the PSU Identity data was last updated March 01, 2024 01:19. Here is the affiliation field:
```
"affiliation": [
      "FACULTY",
      "MEMBER"
    ],
```

@ajkiessl This is not very urgent to fix, but it would be nice if you could take a quick look soon before the relevant data gets overwritten, in case there's info I didn't include here that we'll want when we do fix this. Thanks!

LibAnswers ticket from user (login required -- Ana can share details if needed): https://psu.libanswers.com/admin/ticket?qid=13368443

**Comment by ajkiessl** [comment]
@anaelizabethenriquez That user is still in the directory services as an employed faculty member.  If you use the directory search: https://directory.psu.edu and login to see their details, they are still faculty.  We may need to submit a helpdesk ticket for this.  It'll need fixed at the source.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl I heard back from the researcher. He has an adjunct appointment because he is wrapping up advising work for a few graduate students. I think RMD behaved as it should; sorry for the unnecessary ticket.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Ah okay.  Thanks for looking into it.  I'll close this ticket.
