### ISSUE TITLE
Send OA reminder emails at 1200 UTC on Mondays

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#959]
It seems like the timing of the OA reminder emails has been creeping backward. This week I see they went out around 11 p.m. Sunday. 

If possible, it would be nice to set them to begin sending at a set time -- 7 a.m. Eastern on Monday. We are starting to see folks replying to us Sunday night. 

Update: Let's do 1200 (noon) UTC, which will be 7 a.m. Eastern Standard and 8 a.m. Eastern Daylight.

**Comment by ajkiessl** [comment]
This is happening more frequently lately.  We might want to look in to how large the email is that fails.  It could be that there's a user with a lot of publications listed, and there's an email that times out because it takes a while to send.

**Comment by anaelizabethenriquez** [comment]
OA reminder emails went out this week, but I don't think they sent at 1200 UTC. The timestamps in RMD (which I believe are now in UTC) say "January 20, 2025 03:00". The reply emails we've gotten suggest they sent at 10 p.m. Eastern on Sunday night, which would be the same as 300 UTC (since we're not on Daylight Savings right now).

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Ah, looks like the changes never deployed.  I guess we need to plan a deploy for these infrastructure changes; I assumed they'd sync when we deployed the application (I was wrong).  I added an issue for this to the project board.  We can plan to deploy this on Thursday after retro.
