### ISSUE TITLE
502 errors when exporting publication data

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-libraries/researcher-metadata#969]
I've run into a lot of 502 errors this morning when trying to export what I think are pretty small sets of data from RMD. I am trying to export [Publications for the Children's Heart Center](https://metadata.libraries.psu.edu/admin/publication/by_organization?org_id=520), which has 455 publications in RMD. I've tried exporting various sets of fields for those records, but I always get a 502 error. Finally I tried exporting DOIs only, but that failed too.

@ajkiessl Not sure if this is a sign of anything bigger, or if there's an easy fix, but I wanted to give you a heads up. Thanks!

**Comment by ajkiessl** [comment]
@anaelizabethenriquez I think exporting when publications are filtered by organization confuses some of the RailsAdmin features a little.  Make sure you are exporting with the "Export Found Publications" button in the top right corner of the list page.  I was able to get this to export those publications with just their DOIs.  Could you try that with the fields you wanted?

When I tried exporting just the DOIs using the "Export" tab at the top of the list page, it gave me an error.  I think this tries to export all publications in RMD, though.

Let me know if this doesn't work and I can pull the data with my local set up.  

We will have to consider how we want to handle this export feature in future development cycles.  The whole export process runs in a single thread, so if there's a lot of data and it takes a long time to generate the CSV, the webserver times out (502 or 504 errors).
